version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - network
    restart: unless-stopped

  flyway:
    image: flyway/flyway:9-alpine
    command: -connectRetries=60 -baselineVersion="0.0" baseline migrate info
    volumes:
      - ../flyway/sql:/flyway/sql:ro
    environment:
      - FLYWAY_URL=${DB_URL}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - network

volumes:
  postgres:
networks:
  network:
